name: secret scan

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "53 13 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: ./scripts/check-secrets.sh
